name: 云编译 kmod-rkp-ipid.ipk

on:
  workflow_dispatch:
    inputs:
      openwrt_branch:
        description: "选择 OpenWRT 源码分支"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - openwrt-23.05
          - openwrt-22.03

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    steps:
      - name: 安装系统依赖包
        run: |
          sudo apt update && sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget curl

      - name: 克隆 OpenWRT 源码并同步 feeds
        run: |
          git clone -b ${{ github.event.inputs.openwrt_branch }} https://github.com/openwrt/openwrt.git openwrt-src
          cd openwrt-src
          rm -rf feeds/packages/lang/glib2
          ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: 部署 rkp-ipid 项目源码
        run: |
          mkdir -p openwrt-src/package/custom/rkp-ipid
          git clone https://github.com/CHN-beta/rkp-ipid.git openwrt-src/package/custom/rkp-ipid
          chmod -R 755 openwrt-src/package/custom/rkp-ipid
          echo "=== 验证源码目录 ==="
          ls -l openwrt-src/package/custom/rkp-ipid

      - name: 配置编译选项（关键：启用 kmod-rkp-ipid）
        run: |
          cd openwrt-src
          make defconfig
          # 修正编译开关：从 CONFIG_PACKAGE_rkp-ipid 改为 CONFIG_PACKAGE_kmod-rkp-ipid
          echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
          echo "CONFIG_PACKAGE_luci=n" >> .config && echo "CONFIG_BUILD_LOG=y" >> .config
          make menuconfig -o .config
          # 验证 kmod-rkp-ipid 配置是否生效
          echo "=== 验证编译开关 ==="
          cat .config | grep CONFIG_PACKAGE_kmod-rkp-ipid

      - name: 清理旧产物并编译
        run: |
          cd openwrt-src
          # 清理 kmod-rkp-ipid 旧产物
          make package/rkp-ipid/clean V=s
          # 编译 kmod-rkp-ipid（项目 Makefile 会生成带 kmod 前缀的包）
          make package/rkp-ipid/compile V=s -j$(nproc)
          # 验证 kmod-rkp-ipid.ipk 是否存在
          echo "=== 验证产物 ==="
          find openwrt-src/bin/packages -name "kmod-rkp-ipid_*.ipk"

      - name: 上传 kmod-rkp-ipid 产物
        uses: actions/upload-artifact@v4
        with:
          name: kmod-rkp-ipid-${{ github.event.inputs.openwrt_branch }}
          # 匹配 kmod-rkp-ipid 产物路径
          path: openwrt-src/bin/packages/**/kmod-rkp-ipid_*.ipk
          if-no-files-found: error
          compression-level: 6
          retention-days: 7
