name: Build kmod-rkp-ipid for IPQ6000

on:
  push:
    branches: [ main ]
    paths:
      - 'package/kmod-rkp-ipid/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build kmod-rkp-ipid IPK

    steps:
      - name: Checkout project code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: 'project'

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib gettext \
            git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          df -h

      - name: Clone OpenWRT source
        run: |
          git clone -b openwrt-23.05 --depth 1 https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Integrate kmod-rkp-ipid package
        run: |
          mkdir -p openwrt/package/kmod-rkp-ipid
          cp -r $GITHUB_WORKSPACE/project/package/kmod-rkp-ipid/* openwrt/package/kmod-rkp-ipid/

      - name: Configure build for IPQ6000
        run: |
          cd openwrt
          
          echo "CONFIG_TARGET_ipq60xx=y" > .config
          echo "CONFIG_TARGET_ipq60xx_generic=y" >> .config
          echo "CONFIG_TARGET_ipq60xx_generic_DEVICE_qcom_ipq6000=y" >> .config
          
          echo "CONFIG_DEVEL=y" >> .config
          echo "CONFIG_TOOLCHAINOPTS=y" >> .config
          echo "CONFIG_BUILD_PATENTED=y" >> .config
          echo "CONFIG_KERNEL_BUILD_USER=\"GitHubActions\"" >> .config
          echo "CONFIG_KERNEL_BUILD_DOMAIN=\"github.com\"" >> .config
          
          echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
          
          make defconfig

      - name: Build kmod-rkp-ipid
        run: |
          cd openwrt
          make -j$(nproc) package/kmod-rkp-ipid/compile V=s

      - name: Collect compiled IPK
        run: |
          cd openwrt
          find ./bin/packages -name "kmod-rkp-ipid*.ipk" -exec ls -lh {} \;
          mkdir -p $GITHUB_WORKSPACE/ipk-output
          find ./bin/packages -name "kmod-rkp-ipid*.ipk" -exec cp {} $GITHUB_WORKSPACE/ipk-output/ \;

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4  # 已升级到最新的v4版本
        with:
          name: kmod-rkp-ipid-ipq6000
          path: ipk-output/
          retention-days: 7
    
