name: Build for JDCloud AX1800 (IPQ6000)

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup complete build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync \
          unzip zlib1g-dev file wget bc m4 ccache libelf-dev \
          texinfo pkg-config automake autoconf libtool

    - name: Clone ImmortalWrt source for IPQ6000
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git openwrt-build-ax1800
        cd openwrt-build-ax1800
        git checkout v23.05.3

    - name: Update feeds
      run: |
        cd openwrt-build-ax1800
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add rkp-ipid package
      run: |
        cd openwrt-build-ax1800
        mkdir -p package/kernel/rkp-ipid
        cp -r $GITHUB_WORKSPACE/src package/kernel/rkp-ipid/
        cp -r $GITHUB_WORKSPACE/Makefile package/kernel/rkp-ipid/
        if [ -d "$GITHUB_WORKSPACE/patches" ]; then
          cp -r $GITHUB_WORKSPACE/patches package/kernel/rkp-ipid/
        fi

    - name: Configure for JDCloud AX1800
      run: |
        cd openwrt-build-ax1800
        cat > .config << 'EOF'
CONFIG_TARGET_qualcommax=y
CONFIG_TARGET_qualcommax_ipq60xx=y
CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_jdcloud_ax1800-pro=y
CONFIG_PACKAGE_kmod-rkp-ipid=y
EOF
        make defconfig

    - name: Download dependencies
      run: |
        cd openwrt-build-ax1800
        for i in {1..3}; do
          make download -j$(nproc) && break || sleep 10
        done

    - name: Build kernel preparation
      run: |
        cd openwrt-build-ax1800
        make target/linux/prepare V=s

    - name: Compile kmod-rkp-ipid
      run: |
        cd openwrt-build-ax1800
        make package/kernel/rkp-ipid/compile V=s -j$(nproc) || make package/kernel/rkp-ipid/compile V=s -j1

    - name: Find IPK files
      run: |
        cd openwrt-build-ax1800
        mkdir -p $GITHUB_WORKSPACE/artifacts-ax1800
        IPK_FILES=$(find bin -name "*rkp-ipid*.ipk" 2>/dev/null || true)
        if [ -n "$IPK_FILES" ]; then
          echo "Found IPK files:"
          echo "$IPK_FILES"
          echo "$IPK_FILES" | xargs -I {} cp {} $GITHUB_WORKSPACE/artifacts-ax1800/
        else
          echo "Searching for any IPK files in bin directory:"
          find bin -name "*.ipk" | head -5
        fi

    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kmod-rkp-ipid-ax1800
        path: artifacts-ax1800/
        retention-days: 30
        if-no-files-found: warn
